DX_Labs_SWP391/src/java/models/Accounts.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

/**
 *
 * @author ADMIN
 */
public class Accounts {

    private int ID;
    private String userName, pass, img, isActive;
    private int role;
    private String email;
    private String fullname;

    public Accounts() {
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Accounts(String fullname) {
        this.fullname = fullname;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public Accounts(int ID, String userName, String pass, String img, String isActive, int role) {
        this.ID = ID;
        this.userName = userName;
        this.pass = pass;
        this.img = img;
        this.isActive = isActive;
        this.role = role;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getIsActive() {
        return isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    public int getRole() {
        return role;
    }

    public void setRole(int role) {
        this.role = role;
    }

}

DX_Labs_SWP391/src/java/models/Announcement.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

import java.sql.Date;

/**
 *
 * @author admin
 */
public class Announcement {
    public int Announcement_ID;
    public String Announcement_content;
    public String Description;
   
    public Date Date;

    public Announcement() {
    }

    public Announcement(int Announcement_ID, String Announcement_content, String Description,  Date Date) {
        this.Announcement_ID = Announcement_ID;
        this.Announcement_content = Announcement_content;
        this.Description = Description;
      
        this.Date = Date;
    }

    public int getAnnouncement_ID() {
        return Announcement_ID;
    }

    public void setAnnouncement_ID(int Announcement_ID) {
        this.Announcement_ID = Announcement_ID;
    }

    public String getAnnouncement_content() {
        return Announcement_content;
    }

    public void setAnnouncement_content(String Announcement_content) {
        this.Announcement_content = Announcement_content;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    

    public Date getDate() {
        return Date;
    }

    public void setDate(Date Date) {
        this.Date = Date;
    }

    @Override
    public String toString() {
        return "Announcement{" + "Announcement_ID=" + Announcement_ID + ", Announcement_content=" + Announcement_content + ", Description=" + Description + " Date=" + Date + '}';
    }
    
    
}

DX_Labs_SWP391/src/java/models/Intern_Student.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

import java.sql.Date;

/**
 *
 * @author ThinkPro
 */
public class Intern_Student {

    private int Intern_ID, User_ID, Group_ID, Semester_ID, Mentor_ID, OverallEval_ID;
    private String StudentID, Division, Group_Name, FullName, Comment_Midterm, Comment_Final, Address, Phone_number, Email, ID_Card, Major, Job_tile, Company, Link_CV;
    private Date DOB;
    private Boolean IsLeader, InternStatus, CV_Status;
    private float SoftSkillPoint_Midterm, SoftSkillPoint_Final,
            MajorSkillPoint_Midterm, MajorSkillPoint_Final,
            AttitudePoint_Midterm, AttitudePoint_Final,
            MajorSkillPoint_Overall, SoftSkillPoint_Overall, AttitudePoint_Overall, FinalResult_Overall,
            SemesterID_Overall;

    public Intern_Student(int Intern_ID, int User_ID, int Group_ID, int Semester_ID, int Mentor_ID, int OverallEval_ID, String StudentID, String Division, String Group_Name, String FullName, String Comment_Midterm, String Comment_Final, String Address, String Phone_number, String Email, String ID_Card, String Major, String Job_tile, String Company, String Link_CV, Date DOB, Boolean IsLeader, Boolean InternStatus, Boolean CV_Status, float SoftSkillPoint_Midterm, float SoftSkillPoint_Final, float MajorSkillPoint_Midterm, float MajorSkillPoint_Final, float AttitudePoint_Midterm, float AttitudePoint_Final, float MajorSkillPoint_Overall, float SoftSkillPoint_Overall, float AttitudePoint_Overall, float FinalResult_Overall, float SemesterID_Overall) {
        this.Intern_ID = Intern_ID;
        this.User_ID = User_ID;
        this.Group_ID = Group_ID;
        this.Semester_ID = Semester_ID;
        this.Mentor_ID = Mentor_ID;
        this.OverallEval_ID = OverallEval_ID;
        this.StudentID = StudentID;
        this.Division = Division;
        this.Group_Name = Group_Name;
        this.FullName = FullName;
        this.Comment_Midterm = Comment_Midterm;
        this.Comment_Final = Comment_Final;
        this.Address = Address;
        this.Phone_number = Phone_number;
        this.Email = Email;
        this.ID_Card = ID_Card;
        this.Major = Major;
        this.Job_tile = Job_tile;
        this.Company = Company;
        this.Link_CV = Link_CV;
        this.DOB = DOB;
        this.IsLeader = IsLeader;
        this.InternStatus = InternStatus;
        this.CV_Status = CV_Status;
        this.SoftSkillPoint_Midterm = SoftSkillPoint_Midterm;
        this.SoftSkillPoint_Final = SoftSkillPoint_Final;
        this.MajorSkillPoint_Midterm = MajorSkillPoint_Midterm;
        this.MajorSkillPoint_Final = MajorSkillPoint_Final;
        this.AttitudePoint_Midterm = AttitudePoint_Midterm;
        this.AttitudePoint_Final = AttitudePoint_Final;
        this.MajorSkillPoint_Overall = MajorSkillPoint_Overall;
        this.SoftSkillPoint_Overall = SoftSkillPoint_Overall;
        this.AttitudePoint_Overall = AttitudePoint_Overall;
        this.FinalResult_Overall = FinalResult_Overall;
        this.SemesterID_Overall = SemesterID_Overall;
    }

    public String getComment_Midterm() {
        return Comment_Midterm;
    }

    public void setComment_Midterm(String Comment_Midterm) {
        this.Comment_Midterm = Comment_Midterm;
    }

    public int getOverallEval_ID() {
        return OverallEval_ID;
    }

    public void setOverallEval_ID(int OverallEval_ID) {
        this.OverallEval_ID = OverallEval_ID;
    }

    public float getMajorSkillPoint_Overall() {
        return MajorSkillPoint_Overall;
    }

    public void setMajorSkillPoint_Overall(float MajorSkillPoint_Overall) {
        this.MajorSkillPoint_Overall = MajorSkillPoint_Overall;
    }

    public float getSoftSkillPoint_Overall() {
        return SoftSkillPoint_Overall;
    }

    public void setSoftSkillPoint_Overall(float SoftSkillPoint_Overall) {
        this.SoftSkillPoint_Overall = SoftSkillPoint_Overall;
    }

    public float getAttitudePoint_Overall() {
        return AttitudePoint_Overall;
    }

    public void setAttitudePoint_Overall(float AttitudePoint_Overall) {
        this.AttitudePoint_Overall = AttitudePoint_Overall;
    }

    public float getFinalResult_Overall() {
        return FinalResult_Overall;
    }

    public void setFinalResult_Overall(float FinalResult_Overall) {
        this.FinalResult_Overall = FinalResult_Overall;
    }

    public float getSemesterID_Overall() {
        return SemesterID_Overall;
    }

    public void setSemesterID_Overall(float SemesterID_Overall) {
        this.SemesterID_Overall = SemesterID_Overall;
    }

    public String getComment_Final() {
        return Comment_Final;
    }

    public void setComment_Final(String Comment_Final) {
        this.Comment_Final = Comment_Final;
    }

    public float getSoftSkillPoint_Midterm() {
        return SoftSkillPoint_Midterm;
    }

    public void setSoftSkillPoint_Midterm(float SoftSkillPoint_Midterm) {
        this.SoftSkillPoint_Midterm = SoftSkillPoint_Midterm;
    }

    public float getSoftSkillPoint_Final() {
        return SoftSkillPoint_Final;
    }

    public void setSoftSkillPoint_Final(float SoftSkillPoint_Final) {
        this.SoftSkillPoint_Final = SoftSkillPoint_Final;
    }

    public float getMajorSkillPoint_Midterm() {
        return MajorSkillPoint_Midterm;
    }

    public void setMajorSkillPoint_Midterm(float MajorSkillPoint_Midterm) {
        this.MajorSkillPoint_Midterm = MajorSkillPoint_Midterm;
    }

    public float getMajorSkillPoint_Final() {
        return MajorSkillPoint_Final;
    }

    public void setMajorSkillPoint_Final(float MajorSkillPoint_Final) {
        this.MajorSkillPoint_Final = MajorSkillPoint_Final;
    }

    public float getAttitudePoint_Midterm() {
        return AttitudePoint_Midterm;
    }

    public void setAttitudePoint_Midterm(float AttitudePoint_Midterm) {
        this.AttitudePoint_Midterm = AttitudePoint_Midterm;
    }

    public float getAttitudePoint_Final() {
        return AttitudePoint_Final;
    }

    public void setAttitudePoint_Final(float AttitudePoint_Final) {
        this.AttitudePoint_Final = AttitudePoint_Final;
    }

    public Intern_Student() {
    }

    public int getMentor_ID() {
        return Mentor_ID;
    }

    public void setMentor_ID(int Mentor_ID) {
        this.Mentor_ID = Mentor_ID;
    }

    public String getGroup_Name() {
        return Group_Name;
    }

    public void setGroup_Name(String Group_Name) {
        this.Group_Name = Group_Name;
    }

    public int getIntern_ID() {
        return Intern_ID;
    }

    public void setIntern_ID(int Intern_ID) {
        this.Intern_ID = Intern_ID;
    }

    public int getUser_ID() {
        return User_ID;
    }

    public void setUser_ID(int User_ID) {
        this.User_ID = User_ID;
    }

    public int getGroup_ID() {
        return Group_ID;
    }

    public void setGroup_ID(int Group_ID) {
        this.Group_ID = Group_ID;
    }

    public int getSemester_ID() {
        return Semester_ID;
    }

    public void setSemester_ID(int Semester_ID) {
        this.Semester_ID = Semester_ID;
    }

    public String getStudentID() {
        return StudentID;
    }

    public void setStudentID(String StudentID) {
        this.StudentID = StudentID;
    }

    public String getDivision() {
        return Division;
    }

    public void setDivision(String Division) {
        this.Division = Division;
    }

    public String getFullName() {
        return FullName;
    }

    public void setFullName(String FullName) {
        this.FullName = FullName;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getPhone_number() {
        return Phone_number;
    }

    public void setPhone_number(String Phone_number) {
        this.Phone_number = Phone_number;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getID_Card() {
        return ID_Card;
    }

    public void setID_Card(String ID_Card) {
        this.ID_Card = ID_Card;
    }

    public String getMajor() {
        return Major;
    }

    public void setMajor(String Major) {
        this.Major = Major;
    }

    public String getJob_tile() {
        return Job_tile;
    }

    public void setJob_tile(String Job_tile) {
        this.Job_tile = Job_tile;
    }

    public String getCompany() {
        return Company;
    }

    public void setCompany(String Company) {
        this.Company = Company;
    }

    public String getLink_CV() {
        return Link_CV;
    }

    public void setLink_CV(String Link_CV) {
        this.Link_CV = Link_CV;
    }

    public Date getDOB() {
        return DOB;
    }

    public void setDOB(Date DOB) {
        this.DOB = DOB;
    }

    public Boolean getIsLeader() {
        return IsLeader;
    }

    public void setIsLeader(Boolean IsLeader) {
        this.IsLeader = IsLeader;
    }

    public Boolean getInternStatus() {
        return InternStatus;
    }

    public void setInternStatus(Boolean InternStatus) {
        this.InternStatus = InternStatus;
    }

    public Boolean getCV_Status() {
        return CV_Status;
    }

    public void setCV_Status(Boolean CV_Status) {
        this.CV_Status = CV_Status;
    }

}

DX_Labs_SWP391/src/java/controller/AnswerTaskController.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import DAL.DAOAnswerTask;
import DAL.DAOIntern;
import DAL.DAOTask;
import DAL.GetInternByUserID;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.List;
import models.Accounts;
import models.Answer;
import models.Interns;
import models.Task;

/**
 *
 * @author Laptop K1
 */
public class AnswerTaskController extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet AnswerTaskController</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet AnswerTaskController at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String taskid = request.getParameter("taskID");
        HttpSession session = request.getSession();
        Accounts u = (Accounts) session.getAttribute("acc");
        if (u == null) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }
        DAOIntern dao1 = new DAOIntern();
        Accounts a = (Accounts) session.getAttribute("acc");
        Interns i = dao1.getInternByAccount(a.getID() + "");
        DAOAnswerTask daoa = new DAOAnswerTask();
        DAOTask dao = new DAOTask();
        Answer answer = daoa.getAnswerByTask(taskid);
        List< Task> list1 = dao.getTaskByTaskID1(taskid);
        request.setAttribute("list1", list1);
        request.setAttribute("leader", i);
        request.setAttribute("answer", answer);
        request.getRequestDispatcher("AnswerTask.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

DX_Labs_SWP391/web/AddInternToGroup.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html; charset=UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Intern to Group</title>
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet">

    <!-- Custom Styles -->
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #e6f7ff;
            color: #333;
            margin: 20px;
        }
        h1 {
            color: #005b96;
            text-align: center;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .btn-primary {
            background-color: #007bff;
            color: white;
            border: none;
            transition: background-color 0.3s ease;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <jsp:include page="LeftPanel.jsp"></jsp:include>
    <div id="right-panel" class="right-panel">
        <jsp:include page="rightandheader.jsp"></jsp:include>
        
        <div class="content">
            <div class="container">
                <h1>Add Intern to Group</h1>
                
                <c:set var="i" value="${requestScope.intern}"/>
                <form action="addInternToGroup" method="post">
                    <c:forEach items="${requestScope.student}" var="s">
                        <c:if test="${i.idStudent eq s.roll_number}">
                            <div class="form-group">
                                <label for="intern_id">ID Intern:</label>
                                <input type="text" id="intern_id" readonly name="intern_id" class="form-control" value="${i.idIntern}"/>
                            </div>
                            <div class="form-group">
                                <label for="full_name">Full Name:</label>
                                <input type="text" id="full_name" readonly name="full_name" class="form-control" value="${s.fullname}"/>
                            </div>
                             <div class="form-group">
                                <label for="group_id">Group ID:</label>
                                <input type="text" id="group_id" readonly name="group_id" class="form-control" value="${requestScope.groupId}"/>
                            </div>
                            <button type="submit" class="btn btn-primary">Add To Group</button>
                        </c:if>
                    </c:forEach>
                </form>
            </div>
        </div>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="assets/js/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="assets/js/init/weather-init.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
    <script src="assets/js/init/fullcalendar-init.js"></script>
</body>
</html>

DX_Labs_SWP391/web/DetailAnnouncementForIntern.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Announcement Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
        <link rel="stylesheet" href="assets/css/cs-skin-elastic.css">
        <link rel="stylesheet" href="assets/css/style.css">
        <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
            padding: 20px;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        h1 {
            margin-bottom: 30px;
        }
        .btn-primary {
            background-color: #007bff;
            border: none;
            margin-top: 20px;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
        .table th, .table td {
            vertical-align: middle;
        }
    </style>
</head>
<body>
    <jsp:include page="LeftPanel.jsp"></jsp:include>

            <div id="right-panel" class="right-panel">
            <jsp:include page="rightandheader.jsp"></jsp:include>

    <div class="container">
        <h1 class="text-center">Announcement Details</h1>
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th scope="row">Content</th>
                    <td>${detailannouncement.announcement_content}</td>
                </tr>
                <tr>
                    <th scope="row">Description</th>
                    <td>${detailannouncement.description}</td>
                </tr>
                <tr>
                    <th scope="row">Date</th>
                    <td>${detailannouncement.date}</td>
                </tr>
            </tbody>
        </table>
        <div class="text-center">
            <a href="AnnouncementForIntern" class="btn btn-primary">Back to Announcements</a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
        <script src="assets/js/main.js"></script>
        <!-- Chart js -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

        <!--Chartist Chart-->
        <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
        <script src="assets/js/init/weather-init.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
        <script src="assets/js/init/fullcalendar-init.js"></script>
</body>
</html>

DX_Labs_SWP391/web/hello.jsp
<%-- 
    Document   : hello
    Created on : Jul 11, 2024, 3:17:50 AM
    Author     : Laptop K1
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
       ${mess}
       ${mess1}
       
    </body>
</html>

DX_Labs_SWP391/web/profileDetail.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>